CREATE TABLE `ROLES`(
`ID` INT NOT NULL, -- PRIMARY KEY  
`ROL`VARCHAR(50) NOT NULL,
PRIMARY KEY(`ID`));

CREATE TABLE `USUARIOS`(
`ID` INT NOT NULL AUTO_INCREMENT,-- PRIMARY KEY  
`NOMBRE_APELLIDO`VARCHAR(100) NOT NULL,
`USERNAME`VARCHAR(10) NOT NULL,
`CORREO`VARCHAR(50) NOT NULL,
`CONTRASENA`VARCHAR(10) NOT NULL,
`ROL`INT NOT NULL, -- FOREIGN KEY
PRIMARY KEY(`ID`),
CONSTRAINT `fk_rol` FOREIGN KEY (`ROL`) REFERENCES `ROLES`(`ID`));

CREATE TABLE `MODALIDADES`(
`ID` INT NOT NULL,  -- PRIMARY KEY
`NOMBRE_MODALIDAD`VARCHAR(20) NOT NULL,
PRIMARY KEY(`ID`));

CREATE TABLE `CATEGORIAS`(
`ID` INT NOT NULL,  -- PRIMARY KEY
`NOMBRE_CATEGORIA`VARCHAR(20) NOT NULL,
PRIMARY KEY(`ID`));

CREATE TABLE `GRUPOS`(
`ID` INT NOT NULL,  -- PRIMARY KEY
`NOMBRE_GRUPO`VARCHAR(20) NOT NULL,
PRIMARY KEY(`ID`));

CREATE TABLE `FASES`(
`ID` INT NOT NULL,  -- PRIMARY KEY
`NOMBRE_FASE`VARCHAR(20) NOT NULL,
PRIMARY KEY(`ID`));

CREATE TABLE `EQUIPOS`(
`ID` INT NOT NULL AUTO_INCREMENT,  -- PRIMARY KEY  
`NOMBRE_EQUIPO`VARCHAR(40) NOT NULL,
`MODALIDAD`INT NOT NULL,-- FOREIGN KEY
`CATEGORIA`INT NOT NULL,-- FOREIGN KEY
`ESCUDO_RUTA`VARCHAR(40) NOT NULL,
`DIRECTOR_TÉCNICO`VARCHAR(40) NOT NULL,
`CORREO_ELECTRÓNICO`VARCHAR(40) NOT NULL,
`ACTIVO` BOOLEAN NOT NULL DEFAULT TRUE,
`GRUPO`INT,-- FOREIGN KEY
`FASE`INT, -- FOREIGN KEY
 `PUNTOS`INT,
 `VICTORIAS`INT,
 `DERROTAS`INT,
 `EMPATES`INT,
 `GOLES_ANOTADOS`INT,
 `GOLES_RECIBIDOS`INT,
 PRIMARY KEY(`ID`), 
CONSTRAINT `fk_modalidad` FOREIGN KEY (`MODALIDAD`) REFERENCES `MODALIDADES`(`ID`),
CONSTRAINT `fk_categoria` FOREIGN KEY (`CATEGORIA`) REFERENCES `CATEGORIAS`(`ID`),
CONSTRAINT `fk_grupo` FOREIGN KEY (`GRUPO`) REFERENCES `GRUPOS`(`ID`),
CONSTRAINT `fk_fase` FOREIGN KEY (`FASE`) REFERENCES `FASES`(`ID`));

CREATE TABLE `PARTIDOS`(
`ID` INT NOT NULL AUTO_INCREMENT,-- PRIMARY KEY  
`FASE_CAMPEONATO`INT NOT NULL,-- FOREIGN KEY
`CATEGORIA` INT NOT NULL,-- FOREIGN KEY
`EQUIPO_LOCAL` INT NOT NULL,-- FOREIGN KEY
`EQUIPO_VISITANTE`INT NOT NULL,-- FOREIGN KEY
`GRUPO` INT, -- FOREIGN KEY
`FECHA`DATE NOT NULL,
`GOLES_LOCAL` INT,
`GOLES_VISITANTE` INT,
PRIMARY KEY(`ID`),
CONSTRAINT `fk_fase_campeonato` FOREIGN KEY (`FASE_CAMPEONATO`) REFERENCES `FASES`(`ID`),
CONSTRAINT `fk_categoria_equipos` FOREIGN KEY (`CATEGORIA`) REFERENCES `CATEGORIAS`(`ID`),
CONSTRAINT `fk_grupo_equipos` FOREIGN KEY (`GRUPO`) REFERENCES `GRUPOS`(`ID`),
CONSTRAINT `fk_equipo_local` FOREIGN KEY (`EQUIPO_LOCAL`) REFERENCES `EQUIPOS`(`ID`),
CONSTRAINT `fk_equipo_visitante` FOREIGN KEY (`EQUIPO_VISITANTE`) REFERENCES `EQUIPOS`(`ID`));

INSERT INTO `champions_project`.`ROLES` VALUES
('1', 'USUARIO'),
('2', 'ADMINISTRADOR'),
('3', 'VISITANTE');

INSERT INTO `champions_project`.`MODALIDADES` VALUES
('1', 'FÚTBOL'),
('2', 'MICROFÚTBOL'),
('3', 'FUTBOLSALA');

INSERT INTO `champions_project`.`CATEGORIAS` VALUES
('1', 'FEMENINA'),
('2', 'MASCULINA');

INSERT INTO `champions_project`.`FASES` VALUES
('1', 'GRUPOS'),
('2', 'CUARTOS'),
('3', 'SEMIFINAL'),
('4', 'FINAL');

INSERT INTO `champions_project`.`GRUPOS` VALUES
('1', 'GRUPO A'),
('2', 'GRUPO B'),
('3', 'GRUPO C'),
('4', 'GRUPO D');


/*INSERT INTO champions_project.REGISTRO_EQUIPOS VALUES
(1, 'UFPS'),
('2', 'UIS'),
('3', 'UMB'),
('4', 'EAN'),
('5', 'UTS'),
('6', 'UNIMINUTO'),
('7', 'UNAB'),
('8', 'UNAD'),
('9', 'UPONTIFICIA'),
('10', 'USANTOTO'),
('11', 'USB'),
('12', 'UNIPAMPLONA'),
('13', 'UDI'),
('14', 'UCOOPERATIVA_COLOMBIA'),
('15', 'ESAP'),
('16', 'UDES');*/

